"use client";
import { ArrowUpRight,Code2,Copy,Link2,Mail } from "lucide-react";
import { FormEvent,useState } from "react";
import { profile } from "@/lib/data";
export default function Contact(){
  const[copied,setCopied]=useState(false);const[status,setStatus]=useState<"idle"|"loading"|"draft"|"error">("idle");
  async function copy(){await navigator.clipboard.writeText(profile.email);setCopied(true);setTimeout(()=>setCopied(false),1800)}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(!form.checkValidity()){form.reportValidity();setStatus("error");return}const data=new FormData(form);setStatus("loading");const subject=String(data.get("subject")||"");const body=`Name: ${data.get("name")}\nEmail: ${data.get("email")}\n\n${data.get("message")}`;try{window.location.href=`mailto:${profile.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setStatus("draft")}catch{setStatus("error")}}
  return <section id="contact" className="section contact-section clean-contact"><div className="shell"><div className="contact-main"><div><p><b>06</b> — LET&apos;S CONNECT</p><h2>Have a Project<br/><span>in&nbsp;Mind?</span></h2><p>I&apos;m open to meaningful conversations about software, opportunities, and useful products.</p></div><a className="button primary magnetic" href={`mailto:${profile.email}`}>Send me a message <ArrowUpRight/></a></div><div className="contact-workspace"><form className="contact-form" onSubmit={submit} noValidate><div className="field-row"><label><span>Name</span><input name="name" autoComplete="name" required placeholder="Your name"/></label><label><span>Email</span><input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label></div><label><span>Subject</span><input name="subject" required placeholder="What would you like to discuss?"/></label><label><span>Message</span><textarea name="message" required minLength={10} rows={5} placeholder="Tell me about your project or opportunity."/></label><div className="form-submit"><button className="button primary magnetic" type="submit" disabled={status==="loading"}>{status==="loading"?"Opening mail app…":"Send message"}<ArrowUpRight/></button><p role="status">{status==="draft"?"Your email app was opened with this message as a draft. Review it there, then send.":status==="error"?"Please complete every field with a valid email address.":"This form prepares a draft in your email app; it does not send automatically."}</p></div></form><div className="contact-links"><a href={`mailto:${profile.email}`}><Mail/><span><small>EMAIL</small>{profile.email}</span></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Link2/><span><small>LINKEDIN</small>Hammad Ameer</span></a><a href={profile.github} target="_blank" rel="noreferrer"><Code2/><span><small>GITHUB</small>hammadameer-8525</span></a><button onClick={copy} type="button"><Copy/><span><small>QUICK ACTION</small>{copied?"Email copied":"Copy email"}</span></button></div></div></div></section>
}
