import { ArrowDown,ArrowUpRight,Braces,Code2,Database,FileCode2,HeartPulse,MessagesSquare } from "lucide-react";
import Image from "next/image";
import type { ReactNode } from "react";
import { academicProjects,projects,type Project } from "@/lib/data";

function ProjectVisual({project}:{project:Project}){
  const media=<div className={`project-media ${project.imageType}`}>
    <div className="browser-bar" aria-hidden="true"><i/><i/><i/><span>{project.visualType==="real"?"REAL WEBSITE":"CONCEPT VISUAL"}</span></div>
    {project.image&&<Image src={project.image} alt={project.imageAlt??project.title} fill sizes="(max-width: 900px) calc(100vw - 40px), (max-width: 1400px) 58vw, 780px"/>}
    {project.visualType==="concept"&&<span className="cover-label">CONCEPT VISUAL</span>}
  </div>;
  return project.liveUrl?<a className="project-visual-link" href={project.liveUrl} target="_blank" rel="noopener noreferrer" aria-label={`Open ${project.title} live website`}>{media}</a>:media;
}
function ProjectActions({project}:{project:Project}){const actions=[project.liveUrl&&{label:"LIVE WEBSITE",href:project.liveUrl,external:true,icon:<ArrowUpRight/>},project.githubUrl&&{label:"SOURCE",href:project.githubUrl,external:true,icon:<Code2/>},project.apkFile&&{label:"DOWNLOAD APK",href:project.apkFile,download:true,icon:<ArrowDown/>},!project.apkFile&&project.apkUrl&&{label:"DOWNLOAD APK",href:project.apkUrl,external:true,icon:<ArrowDown/>}].filter(Boolean) as {label:string;href:string;external?:boolean;download?:boolean;icon:ReactNode}[];if(!actions.length)return null;return <div className="project-actions">{actions.map(action=><a key={action.label} href={action.href} target={action.external?"_blank":undefined} rel={action.external?"noopener noreferrer":undefined} download={action.download||undefined}>{action.label} {action.icon}</a>)}</div>}
function FeaturedProject({project,index}:{project:Project;index:number}){return <article id={project.id} className={`featured-row project-${index+1}`}><ProjectVisual project={project}/><div className="featured-copy"><div className="project-meta"><span>{project.number}</span><div className="project-status">{project.status}</div></div><p>{project.id==="stockpilot"?"SAAS / INVENTORY AUTOMATION":project.id==="ownchat"?"MESSAGING PRODUCT":"SELECTED WORK"}</p><h3>{project.title}</h3><p>{project.description}</p><ProjectActions project={project}/></div></article>}
const archiveIcons=[Database,Braces,MessagesSquare,FileCode2,HeartPulse];
export default function Projects(){return <section id="projects" className="section section-alt clean-projects"><div className="shell"><div className="section-heading clean-heading"><p><b>02</b> — FEATURED WORK</p><h2>Projects That Create<br/><span>Impact.</span></h2><small>Real website captures are labeled clearly; original concept visuals represent projects whose product screenshots are not yet available.</small></div><div className="featured-list">{projects.map((p,i)=><FeaturedProject project={p} index={i} key={p.id}/>)}</div><div id="academic-archive" className="archive-clean"><div><p>ACADEMIC ARCHIVE</p><h3>More projects, built from strong fundamentals.</h3></div><span>{String(academicProjects.length).padStart(2,"0")} DOCUMENTED BUILDS</span></div><div className="archive-list">{academicProjects.map((p,index)=>{const Icon=archiveIcons[index];return <article className={`archive-card archive-${index+1}`} key={p.id}><div className="archive-card-top"><span>{p.number}</span><i><Icon/></i></div><h4>{p.title}</h4><p>{p.description}</p><ul>{p.tech.map(tech=><li key={tech}>{tech}</li>)}</ul><ArrowUpRight className="archive-arrow" aria-hidden="true"/></article>})}</div></div></section>}
